export interface MarketChip {
  id: string;
  name: string;
  emoji: string;
  price: number;
  change: number;
  changePercent: number;
}

export interface FPOOffer {
  id: string;
  fpoName: string;
  fpoLogo: string;
  location: string;
  pincode: string;
  block: string;
  district: string;
  state: string;
  commodity: string;
  price: number;
  quantity: number;
  unit: string;
  quality: string;
  variety: string;
  minOrderQty: number;
  availableFrom: string;
  verified: boolean;
  distance?: string;
  lat?: number;
  lng?: number;
}

export interface Message {
  id: string;
  sender: "buyer" | "fpo";
  senderName: string;
  message: string;
  timestamp: string;
}

export interface Quote {
  quoteNo: string;
  orderNo?: string;
  date: string;
  time: string;
  cropName: string;
  fpoName: string;
  quantity: number;
  unit: string;
  price: number;
  offerPrice: number;
  location: string;
  status: "Open" | "Cancelled" | "Rejected" | "Closed" | "Ordered" | "Accepted" | "Packaging" | "Loading" | "Paid" | "Shipped";
  messages?: Message[];
}

export const marketChips: MarketChip[] = [
  { id: "1", name: "Tomato", emoji: "🍅", price: 11.75, change: 0.5, changePercent: 4.44 },
  { id: "2", name: "Onion", emoji: "🧅", price: 18.20, change: -0.8, changePercent: -4.21 },
  { id: "3", name: "Potato", emoji: "🥔", price: 14.50, change: 1.2, changePercent: 9.02 },
  { id: "4", name: "Wheat", emoji: "🌾", price: 22.30, change: 0.3, changePercent: 1.36 },
  { id: "5", name: "Rice", emoji: "🍚", price: 28.40, change: -0.5, changePercent: -1.73 },
  { id: "6", name: "Cotton", emoji: "🌱", price: 65.80, change: 2.1, changePercent: 3.29 },
  { id: "7", name: "Sugarcane", emoji: "🎋", price: 3.50, change: 0.2, changePercent: 6.06 },
  { id: "8", name: "Mango", emoji: "🥭", price: 45.60, change: -1.5, changePercent: -3.18 },
  { id: "9", name: "Banana", emoji: "🍌", price: 24.80, change: 0.9, changePercent: 3.77 },
  { id: "10", name: "Cabbage", emoji: "🥬", price: 8.90, change: -0.3, changePercent: -3.26 },
  { id: "11", name: "Cauliflower", emoji: "🥦", price: 16.20, change: 1.1, changePercent: 7.28 },
  { id: "12", name: "Chilli", emoji: "🌶️", price: 85.40, change: 3.2, changePercent: 3.89 },
];

export const fpoOffers: FPOOffer[] = [
  {
    id: "1",
    fpoName: "Sunrise Agro Collective",
    fpoLogo: "🌅",
    location: "West Bengal",
    pincode: "700001",
    block: "Barasat",
    district: "North 24 Parganas",
    state: "West Bengal",
    commodity: "Tomato",
    price: 11.50,
    quantity: 500,
    unit: "kg",
    quality: "Grade A",
    variety: "Hybrid",
    minOrderQty: 50,
    availableFrom: "2025-11-10",
    verified: true,
    distance: "12 km",
    lat: 22.7196,
    lng: 88.4863,
  },
  {
    id: "2",
    fpoName: "Green Valley Farmers",
    fpoLogo: "🌿",
    location: "Maharashtra",
    pincode: "411001",
    block: "Haveli",
    district: "Pune",
    state: "Maharashtra",
    commodity: "Onion",
    price: 18.00,
    quantity: 1000,
    unit: "kg",
    quality: "Premium",
    variety: "Red Onion",
    minOrderQty: 100,
    availableFrom: "2025-11-08",
    verified: true,
    distance: "25 km",
    lat: 18.5204,
    lng: 73.8567,
  },
  {
    id: "3",
    fpoName: "Golden Harvest FPO",
    fpoLogo: "🌾",
    location: "Punjab",
    pincode: "141001",
    block: "Ludhiana West",
    district: "Ludhiana",
    state: "Punjab",
    commodity: "Wheat",
    price: 22.20,
    quantity: 2000,
    unit: "kg",
    quality: "Grade A",
    variety: "Durum Wheat",
    minOrderQty: 200,
    availableFrom: "2025-11-12",
    verified: true,
  },
  {
    id: "4",
    fpoName: "Delta Rice Producers",
    fpoLogo: "🌊",
    location: "Andhra Pradesh",
    pincode: "520001",
    block: "Vijayawada Rural",
    district: "Krishna",
    state: "Andhra Pradesh",
    commodity: "Rice",
    price: 28.20,
    quantity: 1500,
    unit: "kg",
    quality: "Basmati",
    variety: "Basmati 1121",
    minOrderQty: 150,
    availableFrom: "2025-11-09",
    verified: true,
  },
  {
    id: "5",
    fpoName: "Mountain Fresh Collective",
    fpoLogo: "⛰️",
    location: "Himachal Pradesh",
    pincode: "171001",
    block: "Shimla Rural",
    district: "Shimla",
    state: "Himachal Pradesh",
    commodity: "Potato",
    price: 14.30,
    quantity: 800,
    unit: "kg",
    quality: "Grade B",
    variety: "Kufri Jyoti",
    minOrderQty: 80,
    availableFrom: "2025-11-11",
    verified: false,
  },
  {
    id: "6",
    fpoName: "Cotton Belt Farmers",
    fpoLogo: "🌱",
    location: "Gujarat",
    pincode: "380001",
    block: "Daskroi",
    district: "Ahmedabad",
    state: "Gujarat",
    commodity: "Cotton",
    price: 65.50,
    quantity: 300,
    unit: "kg",
    quality: "Long Staple",
    variety: "BT Cotton",
    minOrderQty: 30,
    availableFrom: "2025-11-15",
    verified: true,
  },
  {
    id: "7",
    fpoName: "Sweet Harvest Collective",
    fpoLogo: "🎋",
    location: "Uttar Pradesh",
    pincode: "250001",
    block: "Meerut Cantonment",
    district: "Meerut",
    state: "Uttar Pradesh",
    commodity: "Sugarcane",
    price: 3.40,
    quantity: 5000,
    unit: "kg",
    quality: "Grade A",
    variety: "Co 0238",
    minOrderQty: 500,
    availableFrom: "2025-11-13",
    verified: true,
  },
  {
    id: "8",
    fpoName: "Tropical Fruit Growers",
    fpoLogo: "🥭",
    location: "Karnataka",
    pincode: "560001",
    block: "Bangalore North",
    district: "Bangalore",
    state: "Karnataka",
    commodity: "Mango",
    price: 44.50,
    quantity: 600,
    unit: "kg",
    quality: "Export Quality",
    variety: "Alphonso",
    minOrderQty: 60,
    availableFrom: "2025-11-14",
    verified: true,
  },
  {
    id: "9",
    fpoName: "Kerala Banana Producers",
    fpoLogo: "🍌",
    location: "Kerala",
    pincode: "682001",
    block: "Ernakulam",
    district: "Ernakulam",
    state: "Kerala",
    commodity: "Banana",
    price: 24.00,
    quantity: 900,
    unit: "kg",
    quality: "Grade A",
    variety: "Nendran",
    minOrderQty: 90,
    availableFrom: "2025-11-10",
    verified: true,
  },
  {
    id: "10",
    fpoName: "Veggie Valley FPO",
    fpoLogo: "🥬",
    location: "Tamil Nadu",
    pincode: "600001",
    block: "Chennai Central",
    district: "Chennai",
    state: "Tamil Nadu",
    commodity: "Cabbage",
    price: 8.75,
    quantity: 700,
    unit: "kg",
    quality: "Fresh Grade",
    variety: "Green Cabbage",
    minOrderQty: 70,
    availableFrom: "2025-11-09",
    verified: false,
  },
  {
    id: "11",
    fpoName: "Fresh Greens Cooperative",
    fpoLogo: "🥦",
    location: "Haryana",
    pincode: "122001",
    block: "Gurugram",
    district: "Gurugram",
    state: "Haryana",
    commodity: "Cauliflower",
    price: 15.80,
    quantity: 650,
    unit: "kg",
    quality: "Premium",
    variety: "Snowball",
    minOrderQty: 65,
    availableFrom: "2025-11-11",
    verified: true,
  },
  {
    id: "12",
    fpoName: "Spice Route Farmers",
    fpoLogo: "🌶️",
    location: "Andhra Pradesh",
    pincode: "530001",
    block: "Visakhapatnam Urban",
    district: "Visakhapatnam",
    state: "Andhra Pradesh",
    commodity: "Chilli",
    price: 84.00,
    quantity: 400,
    unit: "kg",
    quality: "Export Grade",
    variety: "Guntur Sannam",
    minOrderQty: 40,
    availableFrom: "2025-11-16",
    verified: true,
  },
  {
    id: "13",
    fpoName: "Red Valley Tomato Growers",
    fpoLogo: "🍅",
    location: "Karnataka",
    pincode: "577001",
    block: "Davangere",
    district: "Davangere",
    state: "Karnataka",
    commodity: "Tomato",
    price: 12.20,
    quantity: 750,
    unit: "kg",
    quality: "Grade A+",
    variety: "Roma",
    minOrderQty: 75,
    availableFrom: "2025-11-08",
    verified: true,
  },
  {
    id: "14",
    fpoName: "Golden Fields Agriculture",
    fpoLogo: "🌾",
    location: "Madhya Pradesh",
    pincode: "462001",
    block: "Bhopal",
    district: "Bhopal",
    state: "Madhya Pradesh",
    commodity: "Wheat",
    price: 21.80,
    quantity: 3000,
    unit: "kg",
    quality: "Grade A",
    variety: "Sharbati",
    minOrderQty: 300,
    availableFrom: "2025-11-14",
    verified: true,
  },
  {
    id: "15",
    fpoName: "Coastal Rice Farmers",
    fpoLogo: "🍚",
    location: "Odisha",
    pincode: "751001",
    block: "Bhubaneswar",
    district: "Khordha",
    state: "Odisha",
    commodity: "Rice",
    price: 27.90,
    quantity: 2500,
    unit: "kg",
    quality: "Premium",
    variety: "Swarna",
    minOrderQty: 250,
    availableFrom: "2025-11-12",
    verified: true,
    distance: "42 km",
    lat: 20.2961,
    lng: 85.8245,
  },
].map(offer => ({
  ...offer,
  distance: offer.distance || `${Math.floor(Math.random() * 50) + 5} km`,
  lat: offer.lat || 0,
  lng: offer.lng || 0,
}));

export const mockQuoteHistory: Quote[] = [
  {
    quoteNo: "QT12345678",
    date: "2025-10-15",
    time: "10:30 AM",
    cropName: "Tomato",
    fpoName: "Sunrise Agro Collective",
    quantity: 100,
    unit: "kg",
    price: 11.50,
    offerPrice: 11.50,
    location: "Mumbai",
    status: "Shipped",
    messages: [
      {
        id: "1",
        sender: "buyer",
        senderName: "You",
        message: "Hello, I would like to confirm the delivery schedule for this order.",
        timestamp: "2025-10-15, 11:00 AM",
      },
      {
        id: "2",
        sender: "fpo",
        senderName: "Sunrise Agro Collective",
        message: "Hello! Thank you for your order. We can deliver within 2-3 business days. The tomatoes are fresh from our farm.",
        timestamp: "2025-10-15, 11:30 AM",
      },
      {
        id: "3",
        sender: "buyer",
        senderName: "You",
        message: "That sounds great! Can you provide tracking information once shipped?",
        timestamp: "2025-10-15, 12:00 PM",
      },
      {
        id: "4",
        sender: "fpo",
        senderName: "Sunrise Agro Collective",
        message: "Absolutely! We will send you tracking details via SMS and email once the shipment is dispatched.",
        timestamp: "2025-10-15, 12:15 PM",
      },
      {
        id: "5",
        sender: "fpo",
        senderName: "Sunrise Agro Collective",
        message: "Great news! Your order has been accepted and is being prepared for dispatch. The total amount is ₹1150.00. Please proceed with the payment to confirm.",
        timestamp: "2025-10-15, 3:00 PM",
      },
      {
        id: "6",
        sender: "buyer",
        senderName: "You",
        message: "Payment confirmed! Transaction ID: TXN1234567890. Looking forward to receiving the order.",
        timestamp: "2025-10-15, 3:30 PM",
      },
      {
        id: "7",
        sender: "fpo",
        senderName: "Sunrise Agro Collective",
        message: "Thank you for the payment! Your order is now confirmed and will be dispatched tomorrow morning. You'll receive tracking details by evening.",
        timestamp: "2025-10-15, 4:00 PM",
      },
    ],
  },
  {
    quoteNo: "QT87654321",
    date: "2025-10-20",
    time: "2:45 PM",
    cropName: "Onion",
    fpoName: "Green Valley Farmers",
    quantity: 150,
    unit: "kg",
    price: 18.00,
    offerPrice: 18.00,
    location: "Pune",
    status: "Closed",
    messages: [
      {
        id: "1",
        sender: "buyer",
        senderName: "You",
        message: "Is this quote still available? I need 150kg of onions urgently.",
        timestamp: "2025-10-20, 3:00 PM",
      },
      {
        id: "2",
        sender: "fpo",
        senderName: "Green Valley Farmers",
        message: "Yes, we have the stock available. We can deliver tomorrow if you confirm by 5 PM today.",
        timestamp: "2025-10-20, 3:20 PM",
      },
      {
        id: "3",
        sender: "buyer",
        senderName: "You",
        message: "Perfect! I will confirm the payment shortly.",
        timestamp: "2025-10-20, 3:30 PM",
      },
    ],
  },
  {
    quoteNo: "QT11223344",
    date: "2025-10-25",
    time: "11:15 AM",
    cropName: "Wheat",
    fpoName: "Golden Harvest FPO",
    quantity: 300,
    unit: "kg",
    price: 22.20,
    offerPrice: 22.20,
    location: "Delhi",
    status: "Cancelled",
    messages: [
      {
        id: "1",
        sender: "buyer",
        senderName: "You",
        message: "I need to cancel this order due to change in requirements.",
        timestamp: "2025-10-25, 2:00 PM",
      },
      {
        id: "2",
        sender: "fpo",
        senderName: "Golden Harvest FPO",
        message: "We understand. The order has been cancelled. No cancellation charges apply.",
        timestamp: "2025-10-25, 2:30 PM",
      },
    ],
  },
  {
    quoteNo: "QT55667788",
    date: "2025-11-01",
    time: "4:00 PM",
    cropName: "Rice",
    fpoName: "Delta Rice Producers",
    quantity: 200,
    unit: "kg",
    price: 28.20,
    offerPrice: 28.20,
    location: "Bangalore",
    status: "Rejected",
    messages: [
      {
        id: "1",
        sender: "buyer",
        senderName: "You",
        message: "Can you provide quality certificates for this batch?",
        timestamp: "2025-11-01, 4:30 PM",
      },
      {
        id: "2",
        sender: "fpo",
        senderName: "Delta Rice Producers",
        message: "Unfortunately, we are unable to provide certificates for this particular batch. We apologize for the inconvenience.",
        timestamp: "2025-11-01, 5:00 PM",
      },
      {
        id: "3",
        sender: "buyer",
        senderName: "You",
        message: "I see. I will need to look for another supplier then. Thank you for your transparency.",
        timestamp: "2025-11-01, 5:15 PM",
      },
    ],
  },
];

export const mockOrderHistory: Quote[] = [
  {
    quoteNo: "QT12345678",
    orderNo: "ORD20251015001",
    date: "2025-10-15",
    time: "10:30 AM",
    cropName: "Tomato",
    fpoName: "Sunrise Agro Collective",
    quantity: 100,
    unit: "kg",
    price: 11.50,
    offerPrice: 11.50,
    location: "Mumbai",
    status: "Shipped",
    messages: [
      {
        id: "1",
        sender: "fpo",
        senderName: "Sunrise Agro Collective",
        message: "Your order has been accepted! Total amount: ₹1150.00. Please proceed with advance payment.",
        timestamp: "2025-10-15, 3:00 PM",
      },
      {
        id: "2",
        sender: "buyer",
        senderName: "You",
        message: "Advance payment confirmed! Transaction ID: TXN1234567890",
        timestamp: "2025-10-15, 3:30 PM",
      },
      {
        id: "3",
        sender: "fpo",
        senderName: "Sunrise Agro Collective",
        message: "Payment received! Your order is now being packaged.",
        timestamp: "2025-10-16, 9:00 AM",
      },
      {
        id: "4",
        sender: "fpo",
        senderName: "Sunrise Agro Collective",
        message: "Order is being loaded for dispatch. Expected shipment by evening.",
        timestamp: "2025-10-16, 2:00 PM",
      },
      {
        id: "5",
        sender: "fpo",
        senderName: "Sunrise Agro Collective",
        message: "Your order has been shipped! Tracking ID: TRACK123456. Expected delivery in 2-3 days.",
        timestamp: "2025-10-16, 6:00 PM",
      },
    ],
  },
  {
    quoteNo: "QT99887766",
    orderNo: "ORD20251105002",
    date: "2025-11-05",
    time: "9:00 AM",
    cropName: "Potato",
    fpoName: "Mountain Fresh Collective",
    quantity: 250,
    unit: "kg",
    price: 14.30,
    offerPrice: 14.30,
    location: "Shimla",
    status: "Paid",
    messages: [
      {
        id: "1",
        sender: "fpo",
        senderName: "Mountain Fresh Collective",
        message: "Order accepted! Please make advance payment of ₹3575.00",
        timestamp: "2025-11-05, 10:00 AM",
      },
      {
        id: "2",
        sender: "buyer",
        senderName: "You",
        message: "Advance payment done. TXN: TXN9988776655",
        timestamp: "2025-11-05, 11:00 AM",
      },
      {
        id: "3",
        sender: "fpo",
        senderName: "Mountain Fresh Collective",
        message: "Payment received. Order is being packaged.",
        timestamp: "2025-11-05, 2:00 PM",
      },
      {
        id: "4",
        sender: "fpo",
        senderName: "Mountain Fresh Collective",
        message: "Order loaded and ready for shipment. Please clear final payment.",
        timestamp: "2025-11-06, 10:00 AM",
      },
      {
        id: "5",
        sender: "buyer",
        senderName: "You",
        message: "Final payment cleared. TXN: TXN9988776656",
        timestamp: "2025-11-06, 11:30 AM",
      },
    ],
  },
  {
    quoteNo: "QT44556677",
    orderNo: "ORD20251108003",
    date: "2025-11-08",
    time: "3:30 PM",
    cropName: "Cauliflower",
    fpoName: "Fresh Greens Cooperative",
    quantity: 180,
    unit: "kg",
    price: 15.80,
    offerPrice: 15.80,
    location: "Gurugram",
    status: "Loading",
    messages: [
      {
        id: "1",
        sender: "fpo",
        senderName: "Fresh Greens Cooperative",
        message: "Order accepted! Total: ₹2844.00. Awaiting advance payment.",
        timestamp: "2025-11-08, 4:00 PM",
      },
      {
        id: "2",
        sender: "buyer",
        senderName: "You",
        message: "Payment sent. TXN: TXN4455667788",
        timestamp: "2025-11-08, 5:00 PM",
      },
      {
        id: "3",
        sender: "fpo",
        senderName: "Fresh Greens Cooperative",
        message: "Payment confirmed. Packaging your order now.",
        timestamp: "2025-11-09, 9:00 AM",
      },
      {
        id: "4",
        sender: "fpo",
        senderName: "Fresh Greens Cooperative",
        message: "Order is being loaded for dispatch.",
        timestamp: "2025-11-10, 10:00 AM",
      },
    ],
  },
  {
    quoteNo: "QT33445566",
    orderNo: "ORD20251110004",
    date: "2025-11-10",
    time: "11:00 AM",
    cropName: "Banana",
    fpoName: "Kerala Banana Producers",
    quantity: 200,
    unit: "kg",
    price: 24.00,
    offerPrice: 24.00,
    location: "Ernakulam",
    status: "Packaging",
    messages: [
      {
        id: "1",
        sender: "fpo",
        senderName: "Kerala Banana Producers",
        message: "Order accepted! Amount: ₹4800.00. Please make advance payment.",
        timestamp: "2025-11-10, 12:00 PM",
      },
      {
        id: "2",
        sender: "buyer",
        senderName: "You",
        message: "Advance payment completed. TXN: TXN3344556677",
        timestamp: "2025-11-10, 1:00 PM",
      },
      {
        id: "3",
        sender: "fpo",
        senderName: "Kerala Banana Producers",
        message: "Payment received! We are now packaging your fresh bananas.",
        timestamp: "2025-11-10, 3:00 PM",
      },
    ],
  },
  {
    quoteNo: "QT22334455",
    orderNo: "ORD20251112005",
    date: "2025-11-12",
    time: "2:00 PM",
    cropName: "Chilli",
    fpoName: "Spice Route Farmers",
    quantity: 100,
    unit: "kg",
    price: 84.00,
    offerPrice: 84.00,
    location: "Visakhapatnam",
    status: "Accepted",
    messages: [
      {
        id: "1",
        sender: "fpo",
        senderName: "Spice Route Farmers",
        message: "Your order has been accepted! Total amount: ₹8400.00. Please proceed with advance payment to begin processing.",
        timestamp: "2025-11-12, 3:00 PM",
      },
    ],
  },
  {
    quoteNo: "QT11001100",
    orderNo: "ORD20251113006",
    date: "2025-11-13",
    time: "10:00 AM",
    cropName: "Mango",
    fpoName: "Tropical Fruit Growers",
    quantity: 150,
    unit: "kg",
    price: 44.50,
    offerPrice: 44.50,
    location: "Bangalore",
    status: "Closed",
    messages: [
      {
        id: "1",
        sender: "fpo",
        senderName: "Tropical Fruit Growers",
        message: "Order accepted! Amount: ₹6675.00",
        timestamp: "2025-11-13, 11:00 AM",
      },
      {
        id: "2",
        sender: "buyer",
        senderName: "You",
        message: "Advance payment done. TXN: TXN1100110011",
        timestamp: "2025-11-13, 12:00 PM",
      },
      {
        id: "3",
        sender: "fpo",
        senderName: "Tropical Fruit Growers",
        message: "Order packaged and loaded.",
        timestamp: "2025-11-14, 9:00 AM",
      },
      {
        id: "4",
        sender: "fpo",
        senderName: "Tropical Fruit Growers",
        message: "Please clear final payment for shipment.",
        timestamp: "2025-11-14, 10:00 AM",
      },
      {
        id: "5",
        sender: "buyer",
        senderName: "You",
        message: "Final payment cleared. TXN: TXN1100110012",
        timestamp: "2025-11-14, 11:00 AM",
      },
      {
        id: "6",
        sender: "fpo",
        senderName: "Tropical Fruit Growers",
        message: "Order shipped! Tracking: TRACK789012. Delivered successfully!",
        timestamp: "2025-11-15, 5:00 PM",
      },
    ],
  },
];
