export interface MarketChip {
  id: string;
  name: string;
  emoji: string;
  price: number;
  change: number;
  changePercent: number;
}

export interface FPOOffer {
  id: string;
  fpoName: string;
  fpoLogo: string;
  location: string;
  pincode: string;
  block: string;
  district: string;
  state: string;
  commodity: string;
  price: number;
  quantity: number;
  unit: string;
  quality: string;
  variety: string;
  minOrderQty: number;
  availableFrom: string;
  verified: boolean;
}

export const marketChips: MarketChip[] = [
  { id: "1", name: "Tomato", emoji: "🍅", price: 11.75, change: 0.5, changePercent: 4.44 },
  { id: "2", name: "Onion", emoji: "🧅", price: 18.20, change: -0.8, changePercent: -4.21 },
  { id: "3", name: "Potato", emoji: "🥔", price: 14.50, change: 1.2, changePercent: 9.02 },
  { id: "4", name: "Wheat", emoji: "🌾", price: 22.30, change: 0.3, changePercent: 1.36 },
  { id: "5", name: "Rice", emoji: "🍚", price: 28.40, change: -0.5, changePercent: -1.73 },
  { id: "6", name: "Cotton", emoji: "🌱", price: 65.80, change: 2.1, changePercent: 3.29 },
  { id: "7", name: "Sugarcane", emoji: "🎋", price: 3.50, change: 0.2, changePercent: 6.06 },
  { id: "8", name: "Mango", emoji: "🥭", price: 45.60, change: -1.5, changePercent: -3.18 },
  { id: "9", name: "Banana", emoji: "🍌", price: 24.80, change: 0.9, changePercent: 3.77 },
  { id: "10", name: "Cabbage", emoji: "🥬", price: 8.90, change: -0.3, changePercent: -3.26 },
  { id: "11", name: "Cauliflower", emoji: "🥦", price: 16.20, change: 1.1, changePercent: 7.28 },
  { id: "12", name: "Chilli", emoji: "🌶️", price: 85.40, change: 3.2, changePercent: 3.89 },
];

export const fpoOffers: FPOOffer[] = [
  {
    id: "1",
    fpoName: "Sunrise Agro Collective",
    fpoLogo: "🌅",
    location: "West Bengal",
    pincode: "700001",
    block: "Barasat",
    district: "North 24 Parganas",
    state: "West Bengal",
    commodity: "Tomato",
    price: 11.50,
    quantity: 500,
    unit: "kg",
    quality: "Grade A",
    variety: "Hybrid",
    minOrderQty: 50,
    availableFrom: "2025-11-10",
    verified: true,
  },
  {
    id: "2",
    fpoName: "Green Valley Farmers",
    fpoLogo: "🌿",
    location: "Maharashtra",
    pincode: "411001",
    block: "Haveli",
    district: "Pune",
    state: "Maharashtra",
    commodity: "Onion",
    price: 18.00,
    quantity: 1000,
    unit: "kg",
    quality: "Premium",
    variety: "Red Onion",
    minOrderQty: 100,
    availableFrom: "2025-11-08",
    verified: true,
  },
  {
    id: "3",
    fpoName: "Golden Harvest FPO",
    fpoLogo: "🌾",
    location: "Punjab",
    pincode: "141001",
    block: "Ludhiana West",
    district: "Ludhiana",
    state: "Punjab",
    commodity: "Wheat",
    price: 22.20,
    quantity: 2000,
    unit: "kg",
    quality: "Grade A",
    variety: "Durum Wheat",
    minOrderQty: 200,
    availableFrom: "2025-11-12",
    verified: true,
  },
  {
    id: "4",
    fpoName: "Delta Rice Producers",
    fpoLogo: "🌊",
    location: "Andhra Pradesh",
    pincode: "520001",
    block: "Vijayawada Rural",
    district: "Krishna",
    state: "Andhra Pradesh",
    commodity: "Rice",
    price: 28.20,
    quantity: 1500,
    unit: "kg",
    quality: "Basmati",
    variety: "Basmati 1121",
    minOrderQty: 150,
    availableFrom: "2025-11-09",
    verified: true,
  },
  {
    id: "5",
    fpoName: "Mountain Fresh Collective",
    fpoLogo: "⛰️",
    location: "Himachal Pradesh",
    pincode: "171001",
    block: "Shimla Rural",
    district: "Shimla",
    state: "Himachal Pradesh",
    commodity: "Potato",
    price: 14.30,
    quantity: 800,
    unit: "kg",
    quality: "Grade B",
    variety: "Kufri Jyoti",
    minOrderQty: 80,
    availableFrom: "2025-11-11",
    verified: false,
  },
  {
    id: "6",
    fpoName: "Cotton Belt Farmers",
    fpoLogo: "🌱",
    location: "Gujarat",
    pincode: "380001",
    block: "Daskroi",
    district: "Ahmedabad",
    state: "Gujarat",
    commodity: "Cotton",
    price: 65.50,
    quantity: 300,
    unit: "kg",
    quality: "Long Staple",
    variety: "BT Cotton",
    minOrderQty: 30,
    availableFrom: "2025-11-15",
    verified: true,
  },
  {
    id: "7",
    fpoName: "Sweet Harvest Collective",
    fpoLogo: "🎋",
    location: "Uttar Pradesh",
    pincode: "250001",
    block: "Meerut Cantonment",
    district: "Meerut",
    state: "Uttar Pradesh",
    commodity: "Sugarcane",
    price: 3.40,
    quantity: 5000,
    unit: "kg",
    quality: "Grade A",
    variety: "Co 0238",
    minOrderQty: 500,
    availableFrom: "2025-11-13",
    verified: true,
  },
  {
    id: "8",
    fpoName: "Tropical Fruit Growers",
    fpoLogo: "🥭",
    location: "Karnataka",
    pincode: "560001",
    block: "Bangalore North",
    district: "Bangalore",
    state: "Karnataka",
    commodity: "Mango",
    price: 44.50,
    quantity: 600,
    unit: "kg",
    quality: "Export Quality",
    variety: "Alphonso",
    minOrderQty: 60,
    availableFrom: "2025-11-14",
    verified: true,
  },
  {
    id: "9",
    fpoName: "Kerala Banana Producers",
    fpoLogo: "🍌",
    location: "Kerala",
    pincode: "682001",
    block: "Ernakulam",
    district: "Ernakulam",
    state: "Kerala",
    commodity: "Banana",
    price: 24.00,
    quantity: 900,
    unit: "kg",
    quality: "Grade A",
    variety: "Nendran",
    minOrderQty: 90,
    availableFrom: "2025-11-10",
    verified: true,
  },
  {
    id: "10",
    fpoName: "Veggie Valley FPO",
    fpoLogo: "🥬",
    location: "Tamil Nadu",
    pincode: "600001",
    block: "Chennai Central",
    district: "Chennai",
    state: "Tamil Nadu",
    commodity: "Cabbage",
    price: 8.75,
    quantity: 700,
    unit: "kg",
    quality: "Fresh Grade",
    variety: "Green Cabbage",
    minOrderQty: 70,
    availableFrom: "2025-11-09",
    verified: false,
  },
  {
    id: "11",
    fpoName: "Fresh Greens Cooperative",
    fpoLogo: "🥦",
    location: "Haryana",
    pincode: "122001",
    block: "Gurugram",
    district: "Gurugram",
    state: "Haryana",
    commodity: "Cauliflower",
    price: 15.80,
    quantity: 650,
    unit: "kg",
    quality: "Premium",
    variety: "Snowball",
    minOrderQty: 65,
    availableFrom: "2025-11-11",
    verified: true,
  },
  {
    id: "12",
    fpoName: "Spice Route Farmers",
    fpoLogo: "🌶️",
    location: "Andhra Pradesh",
    pincode: "530001",
    block: "Visakhapatnam Urban",
    district: "Visakhapatnam",
    state: "Andhra Pradesh",
    commodity: "Chilli",
    price: 84.00,
    quantity: 400,
    unit: "kg",
    quality: "Export Grade",
    variety: "Guntur Sannam",
    minOrderQty: 40,
    availableFrom: "2025-11-16",
    verified: true,
  },
  {
    id: "13",
    fpoName: "Red Valley Tomato Growers",
    fpoLogo: "🍅",
    location: "Karnataka",
    pincode: "577001",
    block: "Davangere",
    district: "Davangere",
    state: "Karnataka",
    commodity: "Tomato",
    price: 12.20,
    quantity: 750,
    unit: "kg",
    quality: "Grade A+",
    variety: "Roma",
    minOrderQty: 75,
    availableFrom: "2025-11-08",
    verified: true,
  },
  {
    id: "14",
    fpoName: "Golden Fields Agriculture",
    fpoLogo: "🌾",
    location: "Madhya Pradesh",
    pincode: "462001",
    block: "Bhopal",
    district: "Bhopal",
    state: "Madhya Pradesh",
    commodity: "Wheat",
    price: 21.80,
    quantity: 3000,
    unit: "kg",
    quality: "Grade A",
    variety: "Sharbati",
    minOrderQty: 300,
    availableFrom: "2025-11-14",
    verified: true,
  },
  {
    id: "15",
    fpoName: "Coastal Rice Farmers",
    fpoLogo: "🍚",
    location: "Odisha",
    pincode: "751001",
    block: "Bhubaneswar",
    district: "Khordha",
    state: "Odisha",
    commodity: "Rice",
    price: 27.90,
    quantity: 2500,
    unit: "kg",
    quality: "Premium",
    variety: "Swarna",
    minOrderQty: 250,
    availableFrom: "2025-11-12",
    verified: true,
  },
];
